version: "3"

services:
    nginx:
        image: nginx
        restart: always
        volumes:
            - ./html:/usr/share/nginx/html
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./log/nginx:/var/log/nginx
        ports:
            - 8202:80
            
    php:
        image: hoopan/php:8.1.7
        restart: always
        volumes:
            - ./html:/var/www/html
            - ./etc/php:/usr/local/etc/php
            - ./etc/php-fpm.d:/usr/local/etc/php-fpm.d
            
    mysql:
        image: mysql:8.0.29
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: blog
            MYSQL_USER: blog_user
            MYSQL_PASSWORD: 123456
        volumes:
            - ./mysql:/var/lib/mysql
            - ./etc/mysql/conf.d:/etc/mysql/conf.d
            
    redis:
        image: redis:7.0.2
        restart: always
        volumes:
            - ./redis:/data
            - ./etc/redis/redis.conf:/etc/redis/redis.conf
        command:
            redis-server /etc/redis/redis.conf
